indexPageGreeting : "Index Page Request has been made from Property from main branch from remote repo; and ia working in azure spring cloud; it changes"

updateConfigCronJobScheduleString : "0 0/1 * 1/1 * ?"
